CREATE DATABASE CampaignDB;

USE CampaignDB;

CREATE TABLE Campaign (
    CAMPAIGN_CODE VARCHAR(255) PRIMARY KEY,
    CAMPAIGN_NAME VARCHAR(255),
    CAMPAIGN_START_DATE DATE,
    CAMPAIGN_END_DATE DATE,
    PRE_CAMPAIGN_START_DATE DATE,
    PRE_CAMPAIGN_END_DATE DATE,
    CAMPAIGN_BUDGET DECIMAL(18, 2),
    CAMPAIGN_EXPENSE DECIMAL(18, 2),
    CAMPAIGN_DESC VARCHAR(1000),
    CAMPAIGN_INITIATOR VARCHAR(255),
    CAMPAIGN_MANAGER VARCHAR(255),
    REVENUE_PLAN DECIMAL(18, 2),
    TARGET_CUST_COUNT INT,
    ACTIVE INT
);

CREATE TABLE StagingCampaign (
    CAMPAIGN_CODE VARCHAR(255) PRIMARY KEY,
    CAMPAIGN_NAME VARCHAR(255),
    CAMPAIGN_START_DATE DATE,
    CAMPAIGN_END_DATE DATE,
    PRE_CAMPAIGN_START_DATE DATE,
    PRE_CAMPAIGN_END_DATE DATE,
    CAMPAIGN_BUDGET DECIMAL(18, 2),
    CAMPAIGN_EXPENSE DECIMAL(18, 2),
    CAMPAIGN_DESC VARCHAR(1000),
    CAMPAIGN_INITIATOR VARCHAR(255),
    CAMPAIGN_MANAGER VARCHAR(255),
    REVENUE_PLAN DECIMAL(18, 2),
    TARGET_CUST_COUNT INT,
    ACTIVE INT
);

CREATE TABLE Campaign_delta (
    CAMPAIGN_ID INT IDENTITY(1,1) PRIMARY KEY,
    CAMPAIGN_CODE VARCHAR(255),
    CAMPAIGN_NAME VARCHAR(255),
    CAMPAIGN_START_DATE DATE,
    CAMPAIGN_END_DATE DATE,
    PRE_CAMPAIGN_START_DATE DATE,
    PRE_CAMPAIGN_END_DATE DATE,
    CAMPAIGN_BUDGET DECIMAL(18, 2),
    CAMPAIGN_EXPENSE DECIMAL(18, 2),
    CAMPAIGN_DESC VARCHAR(1000),
    CAMPAIGN_INITIATOR VARCHAR(255),
    CAMPAIGN_MANAGER VARCHAR(255),
    REVENUE_PLAN DECIMAL(18, 2),
    TARGET_CUST_COUNT INT,
    ACTIVE INT,
    CHANGE_TYPE CHAR(1),
    CHANGE_DATE DATETIME
);

CREATE TABLE ETL_Log (
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    LogTimestamp DATETIME DEFAULT GETDATE(),
    StepDescription VARCHAR(255),
    Status VARCHAR(50),
    ErrorMessage VARCHAR(MAX)
);

